create table PRODUCTO(
    ID INTEGER AUTO_INCREMENT,
    CODIGO VARCHAR(50),
    DESCRIPCION VARCHAR(250),
    PRECIO DOUBLE PRECISION,
    EXISTENCIA INTEGER,
    CREATED_AT DATE,
    UPDATED_AT DATE
);