create table PRODUCTO(
    ID INTEGER AUTO_INCREMENT,
    CODIGO VARCHAR(50),
    DESCRIPCION VARCHAR(250),
    FAMILIA VARCHAR(250),
    PRECIO DOUBLE PRECISION,
    EXISTENCIA INTEGER,
    CREATED_AT DATE DEFAULT CURRENT_DATE,
    UPDATED_AT DATE DEFAULT CURRENT_DATE
);